### ISSUE TITLE
Why are all the properties readonly?

### ISSUE THREAD

**Issue by not-my-profile** [EdJoPaTo/wikibase-types#25]
I don't think that a type library should introduce artificial restrictions. If you want to modify these properties you should be able to.

**Comment by EdJoPaTo** [comment]
The types represent data returned by a Wikibase instance. In order to change it, it needs to be changed at their instance, not in the returned data.

Also its a good thing to work with immutable data and create new objects instead of changing existing onces. TypeScript is sadly lacking in this aspect as const ensures nearly nothing and types like `Readonly<T>` are not as useful for multiple layers of objects.

Creating new objects with some changed aspects is relatively easy with the spread pattern:

```ts
const original = {a: 13, b: 37};
const adaptation = {...original, a: 666};
console.log(adaptation);
// {b: 37, a: 666}
```

So yeah, I do personally prefer immutability so this type library reflects that.

Alternatively you might want to check out https://github.com/codeledge/entitree-monorepo/tree/main/packages/entitree-helper/src/types

**Comment by not-my-profile** [comment]
>In order to change it, it needs to be changed at their instance, not in the returned data.

There is such a thing as postprocessing and I do in fact have a use case where I want a function that postprocesses Wikidata in a typesafe manner but without having to create new objects, which is clearly less efficient.
